apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-trading-service-config
  labels:
    app: trading-service
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  PORT: {{ .Values.env.PORT | quote }}
  KAFKA_BROKERS: {{ .Values.env.KAFKA_BROKERS | quote }}
  MATCHING_ENGINE_URL: {{ .Values.env.MATCHING_ENGINE_URL | quote }}
