apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-trading-service
  labels:
    app: trading-service
    app.kubernetes.io/name: trading-service
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: grpc
      protocol: {{ .Values.service.protocol }}
      name: grpc
  selector:
    app: trading-service
    app.kubernetes.io/instance: {{ .Release.Name }}
