apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-web-app
  labels:
    app: web-app
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  selector:
    matchLabels:
      app: web-app
      app.kubernetes.io/instance: {{ .Release.Name }}
