apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-api-gateway
  labels:
    app: api-gateway
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  selector:
    matchLabels:
      app: api-gateway
      app.kubernetes.io/instance: {{ .Release.Name }}
