apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-blockchain
  labels:
    app: blockchain
    app.kubernetes.io/name: blockchain
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.rpcPort }}
      targetPort: rpc
      protocol: TCP
      name: rpc
    - port: {{ .Values.service.p2pPort }}
      targetPort: p2p
      protocol: TCP
      name: p2p
  selector:
    app: blockchain
    app.kubernetes.io/instance: {{ .Release.Name }}
